# Per-MVP env. Lives at /srv/apps/<mvp>/.env.
# Generated by `clientora mvp:add`; edit in place for app-specific vars.

NODE_ENV=production
LOG_LEVEL=info

# Connects to shared Postgres/Redis via the `clientora_data` Docker network.
DATABASE_URL=postgres://{{DB_USER}}:{{DB_PASSWORD}}@postgres:5432/{{DB_NAME}}
REDIS_URL=redis://redis:6379/{{REDIS_DB_INDEX}}

# Public URL (proxied by shared Caddy)
PUBLIC_URL=https://{{DOMAIN}}
API_PUBLIC_URL=https://{{DOMAIN}}
WEB_ORIGIN=https://{{DOMAIN}}

# API
API_PORT=4000

# Auth — generate fresh per deploy target
JWT_ACCESS_SECRET={{JWT_ACCESS_SECRET}}
JWT_REFRESH_SECRET={{JWT_REFRESH_SECRET}}
JWT_ACCESS_TTL=900
JWT_REFRESH_TTL=2592000
SECRETS_ENCRYPTION_KEY={{SECRETS_ENCRYPTION_KEY}}

# WhatsApp — defaults to mock. Switch to `cloud` once Meta credentials are provisioned.
WA_PROVIDER=mock
WA_CLOUD_ACCESS_TOKEN=
WA_CLOUD_PHONE_NUMBER_ID=
WA_CLOUD_VERIFY_TOKEN=

# Email (optional; logs to console if unset)
RESEND_API_KEY=
EMAIL_FROM=noreply@{{DOMAIN}}

# Bootstrap — remove after first login + signup flow lands
BOOTSTRAP_ORG_NAME=Reform Hotel
BOOTSTRAP_ADMIN_EMAIL=admin@{{DOMAIN}}
BOOTSTRAP_ADMIN_PASSWORD={{BOOTSTRAP_ADMIN_PASSWORD}}
